# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/01_look_at_data.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/core/01_look_at_data.ipynb 5
import dementia_inequalities as proj
from .. import const, log, utils, tools
import adu_proj.utils as adutils

# %% ../../nbs/core/01_look_at_data.ipynb 8
log.info('Doing some stuff')
