# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/02_prep_constituency_data.ipynb.

# %% auto 0
__all__ = ['df_pc_age', 'df_pc_eth', 'df_pc_educ']

# %% ../../nbs/core/02_prep_constituency_data.ipynb 5
import dementia_inequalities as proj
from .. import const, log, utils, tools
import adu_proj.utils as adutils

# %% ../../nbs/core/02_prep_constituency_data.ipynb 6
import numpy as np 
import pandas as pd 

# %% ../../nbs/core/02_prep_constituency_data.ipynb 9
df_pc_age = pd.read_excel(const.data_path+'/mid2020parliconsyoaestimatesage.xlsx', sheet_name='Mid-2020 Persons')
df_pc_eth = pd.read_excel(const.data_path+'/ethnicity_2021census.xlsx')
df_pc_educ = pd.read_excel(const.data_path+'/qualifications_2021census.xlsx')
