# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/02_prep_constituency_data.ipynb.

# %% auto 0
__all__ = ['df_pc_age', 'df_pc_eth', 'df_pc_educ', 'df_lad_age', 'df_lad_eth', 'df_lad_educ']

# %% ../../nbs/core/02_prep_constituency_data.ipynb 5
import dementia_inequalities as proj
from .. import const, log, utils, tools
import adu_proj.utils as adutils

# %% ../../nbs/core/02_prep_constituency_data.ipynb 6
import numpy as np 
import pandas as pd 

# %% ../../nbs/core/02_prep_constituency_data.ipynb 10
df_pc_age = pd.read_excel(const.data_path+'/PC_data/mid2020parliconsyoaestimatesage.xlsx', sheet_name='Mid-2020 Persons')
df_pc_eth = pd.read_excel(const.data_path+'/PC_data/ethnicity_2021census.xlsx')
df_pc_educ = pd.read_excel(const.data_path+'/PC_data/qualifications_2021census.xlsx')

# %% ../../nbs/core/02_prep_constituency_data.ipynb 21
df_lad_age = pd.read_excel(const.data_path+'/LAD_data/mid_21_age_pop.xlsx', sheet_name='Population')
df_lad_eth = pd.read_excel(const.data_path+'/LAD_data/ethnicity_2021_census.xlsx')
df_lad_educ = pd.read_excel(const.data_path+'/LAD_data/education_2021_census.xlsx', sheet_name='Dataset')
