# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/01_prep_data.ipynb.

# %% auto 0
__all__ = ['df_QOF_prev']

# %% ../../nbs/core/01_prep_data.ipynb 5
import dementia_inequalities as proj
from .. import const, log, utils, tools
import adu_proj.utils as adutils

# %% ../../nbs/core/01_prep_data.ipynb 6
import numpy as np 
import pandas as pd 

# %% ../../nbs/core/01_prep_data.ipynb 8
# Useful to use this: const.data_path
df_QOF_prev = pd.read_csv(const.data_path+'/QOF_2022-23/PREVALENCE_2223.csv')
#NHS_geograph = pd.read_csv(const.data_path+'/QOF_2022-23/MAPPING_NHS_GEOGRAPHIES_2223.csv')
