# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/02c_merge_LAD_QOF.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/core/02c_merge_LAD_QOF.ipynb 5
import dementia_inequalities as proj
from .. import const, log, utils, tools
import adu_proj.utils as adutils

# %% ../../nbs/core/02c_merge_LAD_QOF.ipynb 6
import numpy as np 
import pandas as pd 
