# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/04_regression_model.ipynb.

# %% auto 0
__all__ = ['df_dem_plus', 'covar_opt', 'x', 'y', 'regr', 'y_pred', 'reg_coefficients']

# %% ../../nbs/core/04_regression_model.ipynb 4
import dementia_inequalities as proj
from .. import const
import adu_proj.utils as adutils

# %% ../../nbs/core/04_regression_model.ipynb 5
import numpy as np 
import pandas as pd 
from matplotlib import pyplot as plt
import matplotlib.font_manager as fm
from sklearn import linear_model
from sklearn.model_selection import KFold, cross_val_score
import itertools

import scipy.stats as st

# %% ../../nbs/core/04_regression_model.ipynb 10
df_dem_plus = pd.read_csv(const.output_path+'/df_dem_plus.csv')

# %% ../../nbs/core/04_regression_model.ipynb 13
# Potential covariates 
covar_opt = ['over_65_pc', 
             'female_pc', 
             'ALevel_plus_pc', 
             'white_pc',
             'GP_LAD_pc']

# %% ../../nbs/core/04_regression_model.ipynb 22
# Linear regression using sklearn 

x = df_dem_plus[covar_opt].values.reshape(-1,len(covar_opt))
y = df_dem_plus['DEM_afflicted_pc'].values.reshape(-1,1)

regr = linear_model.LinearRegression()

# fit regression comorbidities
regr.fit(x, y)
y_pred = regr.predict(x)

# %% ../../nbs/core/04_regression_model.ipynb 24
# save the regression coefficients so that I can use them in a different nb 

reg_coefficients = np.concatenate([regr.intercept_, regr.coef_[0]])
np.save(const.pre_output_path+'/reg_coeff.npy', reg_coefficients)
