# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/05_ml_custom_regression_model.ipynb.

# %% auto 0
__all__ = ['df_dem_plus']

# %% ../../nbs/core/05_ml_custom_regression_model.ipynb 4
import dementia_inequalities as proj 
from .. import const, log, utils, tools 
import adu_proj.utils as adutils 

# %% ../../nbs/core/05_ml_custom_regression_model.ipynb 5
import numpy as np 
import pandas as pd
from matplotlib import pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import KFold, cross_val_score

# pymc
import pymc as pm
from pymc import Normal, HalfNormal

#pyro
import os
import torch
import pyro
from torch import nn 
from pyro.nn import PyroModule


# %% ../../nbs/core/05_ml_custom_regression_model.ipynb 7
df_dem_plus = pd.read_csv(const.output_path+'/df_dem_plus.csv')
