# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/05c_optimise_function.ipynb.

# %% auto 0
__all__ = ['df_dem_plus']

# %% ../../nbs/core/05c_optimise_function.ipynb 2
import autograd.numpy as np
from autograd import grad, jacobian, hessian
from scipy.optimize import minimize
import pandas as pd
from matplotlib import pyplot as plt

from .. import const, log, utils, tools 

# %% ../../nbs/core/05c_optimise_function.ipynb 4
df_dem_plus = pd.read_csv(const.output_path+'/df_dem_plus.csv')
