# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/cli/cli_01_core.ipynb.

# %% auto 0
__all__ = ['cmd_name', 'cmd_description', 'parser', 'args', 'const_dict', 'log_name', 'store_log_path']

# %% ../../nbs/cli/cli_01_core.ipynb 4
import sys

import dementia_inequalities as proj
from .. import const, log, utils, tools, core
import adu_proj.utils as adutils

# %% ../../nbs/cli/cli_01_core.ipynb 6
def main(): pass # This is necessary for console_scripts

# %% ../../nbs/cli/cli_01_core.ipynb 10
if adutils.cli.is_interactive():
    # Create a temporary figs folder to output figures to
    local_path = tempfile.mkdtemp()
    temp_figs_path = Path(local_path, 'figs')
    temp_figs_path.mkdir()
    
    sys.argv = ['', # First element is not parsed by argparse
                '--const-str', f'figs_path={temp_figs_path}',
                '--log-name', 'test_log_name',
                '--no-store-log',
                '--print-log']

# %% ../../nbs/cli/cli_01_core.ipynb 12
cmd_name = 'cli.core'
cmd_description = "Execute package."

# %% ../../nbs/cli/cli_01_core.ipynb 13
## Define arg parser
parser = adutils.cli.get_default_arg_parser()
parser.description = cmd_description

## Parse args and adjust settings
args = parser.parse_args()
const_dict = adutils.cli.set_const_args(const, args)
log_name = cmd_name if not args.log_name else args.log_name
store_log_path = const.logs_path if args.store_log else None
log.settings(log_name, store_log_path=store_log_path, print_log=args.print_log)

## Output all values in const into the log
adutils.cli.log_all_const()

## Run command with settings
core.run_all()
